### PR TITLE
Multiple cookies

### PR DESCRIPTION
**Pull request by Singletoned**
Handles setting multiple cookies through multiple `Set-cookie` headers.  Also adds httpbin when testing, for convenience.  I might expand on this a bit more later.  It makes testing very convenient.

### CODE REVIEW

**Comment by seanbrant** [comment]
Hey thanks for the PR!

What is the requirements.txt needed for? If it's just for installing the test dependancies I believe `make develop` will do that.

Also would you mind writing a test for the multiple header use-case? Just testing the `make_headers` function in isolation would be fine.

**Comment by the-allanc** [comment]
@Singletoned - Hope you don't mind, but I've taken your test and used it in my own WSGI adapter library - [Pyriform](https://github.com/the-allanc/pyriform/commit/979ef62b469a030380fea72b336163646ad4f7d9).

**Comment by Singletoned** [comment]
@seanbrant The requirements.txt is a fairly standard way of declaring development requirements.  A lot of automated build software assumes it is there to be able to tell that it is a Python project and to set it up (like CircleCI or Heroku).

I've added a test using Httpbin, but it breaks the other tests on other versions of Python (like 2.6) because it uses Flask (which has an insane number of dependencies).  I'm currently refactoring Httpbin to not use Flask, and refactoring it's tests to use Requests and Requests-wsgi-adapter (which will test quite a lot of aspects of Requests-wsgi-adapter).

If you don't mind leaving this PR open for a little while, I'll fix it up soon, and open another one later with any fixes from the Requests work.

**Comment by Singletoned** [comment]
@the-allanc No problem, help yourself to anything.  I'm currently rewriting the Httpbin tests to use Requests and an adapter, so you could easily repurpose those for your library once I'm finished.

The changes will be here in a week, I guess, https://github.com/Singletoned/httpbin.

I had a look at your library, and it looks like I'm starting something very similar but from scratch, rather than using WebTest.  I'm not a huge fan of the api of WebTest.

**Comment by Singletoned** [comment]
@seanbrant The tests are passing again now.  I've cleaned things up a bit. It would be good to get this merged so that I can finish rewriting the httpbin test suite to use requests-wsgi-adapter.  Thanks.

**Comment by seanbrant** [comment]
@Singletoned Thanks for the patch I just released `0.4.0` with it.

**Pull request merged**
