### PR TITLE
fix PATH_INFO  according to https://tools.ietf.org/html/rfc3875#section-4.1.5

### PR DESCRIPTION
**Pull request by MuchkoM**
Adapter must return variable PATH_INFO as string in encoding laitin-1
... 
Unlike a URI path, the PATH_INFO is not URL-encoded
...

### CODE REVIEW

**Comment by aparamon** [comment]
@MuchkoM please fix
https://travis-ci.org/seanbrant/requests-wsgi-adapter/jobs/456846416#L584-L585

**Comment by AndreLouisCaron** [comment]
I'd also like this fix.  Seems to me like adding `# coding=`, `# -*- coding: utf-8 -*-` or similar at the top of the file would do it?

**Comment by AndreLouisCaron** [comment]
Seems like the build is failing on versions of Python <3.4 because it tries to install a version of `setuptools` that requires Python 3.4+.

**Comment by aparamon** [comment]
@AndreLouisCaron Yes, see https://github.com/seanbrant/requests-wsgi-adapter/issues/11

**Comment by MuchkoM** [comment]
from urllib.parse import unquote

**Comment by seanbrant** [comment]
I fixed the #11 if you can rebase master I'll take another look this.

**Pull request merged**
