### PR TITLE
Add Python 2.6 support

### PR DESCRIPTION
**Pull request by alexntt**
This passes setup.py test without problem (quick test using Docker:

```
$ docker run -v $(pwd):/usr/local/src -it centos:6
# yum install -y python-setuptools
# easy_install pytest pip
# make test
```

### CODE REVIEW

**Comment by seanbrant** [comment]
This looks good but you shouldn't need the wrapper list. Mind removing that and I'll merge this.

```
dict(
    ('HTTP_{0}'.format(name).replace('-', '_').upper(), value)
    for name, value in request.headers.items()
)
```

**Comment by alexntt** [comment]
`push --force`'d a new commit... not sure about the indentation you prefer. Let me know if you want some other tweak.

**Comment by seanbrant** [comment]
Thanks! I'll cut a new release tonight.

**Comment by alexntt** [comment]
Hi @seanbrant ,

Sorry to be a PITA- the new version breaks on 2.6 for two reasons:

* new requests version seems to have some py26 compatibility issues
* you used datetime.timedelta.totalseconds() which is only in >=2.7

Would you be interested in a PR which fixes that (which will make the totalseconds() bit totally ugly and will introduce complexity to setup.py)? I feel that maintaining py26 compatibility might be annoying to you and I'd be happy to stay on forked code.

If you don't mind the extra complexity of py26 compatibility, I'd be happy to do the PR.

Cheers,

Álex

**Comment by seanbrant** [comment]
Do you have the code already in a forked version that I can look at?

**Comment by alexntt** [comment]
https://github.com/alexntt/requests-wsgi-adapter/commit/9438bf5e21c56a2c8659f543137ce68bc3c96e31 - I am not especially proud of that. There is actually no problem with requests- I must have been confused.

I understand that py26 compatibility is not exactly a worthwhile endeavor- I wouldn't want to burden you too much with that...

**Comment by seanbrant** [comment]
I think I'm going to pass on full 2.6 support for now. If anyone else chimes in needing it I'll reopen this issue.

**Pull request merged**
